### ISSUE TITLE
Support passing a gitleaks .toml to allow custom rules

### ISSUE THREAD

**Issue by Simon-Wyatt** [punk-security/secret-magpie#59]
I really like Gitleaks as a tool because I can add regular expressions to the .toml file, defining secrets I don't want in code.

**Describe the solution you'd like**

Could secret-magpie be updated with an option to pass a custom config file into gitleaks as the --config argument? This would be slightly cleaner than adding an overriding layer to the container images when I pull them.

**Additional context**

_I want to change the gitleaks rules because I can't detect plaintext passwords with the predefined config used by gitleaks 8.15.3. Is this possibly a bug with gitleaks?_

In good news, I've investigated this and the earlier password rules have been rolled into the [generic-api-key rule](https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml#L482-L495).

**Comment by SimonGurney** [comment]
#65
